#include<stdio.h>
#include<conio.h>
int checkPrimeNumber(int n);
void main()
{int n,flag;
clrscr();
printf("SHUBHAM\n");
printf("enter a positive interger=");
scanf("%d",&n);
flag=checkPrimeNumber(n);
if(flag==1)
printf("%d is not a prime number",n);
else
printf("%d is a prime number",n);
getch();}
int checkPrimeNumber(int n)
{int i;
for(i=2;i<=n/2;i++)
{if(n%i==0)
return 1;}
return 0;}